export const SET_FORECAST = 'SET_FORECAST';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_LIKES_ONLOAD = 'SET_LIKES_ONLOAD';
export const MANAGE_FAVORITE = 'MANAGE_FAVORITE';
